// Generated by gencpp from file rss/LocalizationResponse.msg
// DO NOT EDIT!


#ifndef RSS_MESSAGE_LOCALIZATIONRESPONSE_H
#define RSS_MESSAGE_LOCALIZATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace rss
{
template <class ContainerAllocator>
struct LocalizationResponse_
{
  typedef LocalizationResponse_<ContainerAllocator> Type;

  LocalizationResponse_()
    : pose_array()
    , weights()
    , prob_mesh()  {
    }
  LocalizationResponse_(const ContainerAllocator& _alloc)
    : pose_array(_alloc)
    , weights(_alloc)
    , prob_mesh(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _pose_array_type;
  _pose_array_type pose_array;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _weights_type;
  _weights_type weights;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _prob_mesh_type;
  _prob_mesh_type prob_mesh;




  typedef boost::shared_ptr< ::rss::LocalizationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss::LocalizationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizationResponse_

typedef ::rss::LocalizationResponse_<std::allocator<void> > LocalizationResponse;

typedef boost::shared_ptr< ::rss::LocalizationResponse > LocalizationResponsePtr;
typedef boost::shared_ptr< ::rss::LocalizationResponse const> LocalizationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss::LocalizationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss::LocalizationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rss

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rss': ['/home/simoneforno/simon_ws/src/rss/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rss::LocalizationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss::LocalizationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss::LocalizationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss::LocalizationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss::LocalizationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss::LocalizationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss::LocalizationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d22e81275cae00af4cd4542b46c6f30";
  }

  static const char* value(const ::rss::LocalizationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d22e81275cae00aULL;
  static const uint64_t static_value2 = 0xf4cd4542b46c6f30ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss::LocalizationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss/LocalizationResponse";
  }

  static const char* value(const ::rss::LocalizationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss::LocalizationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/PoseArray pose_array\n\
float64[] weights\n\
float64[] prob_mesh\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::rss::LocalizationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss::LocalizationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_array);
      stream.next(m.weights);
      stream.next(m.prob_mesh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss::LocalizationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss::LocalizationResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose_array: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_array);
    s << indent << "weights[]" << std::endl;
    for (size_t i = 0; i < v.weights.size(); ++i)
    {
      s << indent << "  weights[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.weights[i]);
    }
    s << indent << "prob_mesh[]" << std::endl;
    for (size_t i = 0; i < v.prob_mesh.size(); ++i)
    {
      s << indent << "  prob_mesh[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.prob_mesh[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS_MESSAGE_LOCALIZATIONRESPONSE_H
