// Generated by gencpp from file rss/RssDatum.msg
// DO NOT EDIT!


#ifndef RSS_MESSAGE_RSSDATUM_H
#define RSS_MESSAGE_RSSDATUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rss
{
template <class ContainerAllocator>
struct RssDatum_
{
  typedef RssDatum_<ContainerAllocator> Type;

  RssDatum_()
    : rss()  {
    }
  RssDatum_(const ContainerAllocator& _alloc)
    : rss(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _rss_type;
  _rss_type rss;




  typedef boost::shared_ptr< ::rss::RssDatum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss::RssDatum_<ContainerAllocator> const> ConstPtr;

}; // struct RssDatum_

typedef ::rss::RssDatum_<std::allocator<void> > RssDatum;

typedef boost::shared_ptr< ::rss::RssDatum > RssDatumPtr;
typedef boost::shared_ptr< ::rss::RssDatum const> RssDatumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss::RssDatum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss::RssDatum_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rss

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rss': ['/home/simoneforno/simon_ws/src/rss/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rss::RssDatum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss::RssDatum_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss::RssDatum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss::RssDatum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss::RssDatum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss::RssDatum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss::RssDatum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30f9e1fe2cc18569f41e9246340d3ec5";
  }

  static const char* value(const ::rss::RssDatum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30f9e1fe2cc18569ULL;
  static const uint64_t static_value2 = 0xf41e9246340d3ec5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss::RssDatum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss/RssDatum";
  }

  static const char* value(const ::rss::RssDatum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss::RssDatum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[]  rss\n\
";
  }

  static const char* value(const ::rss::RssDatum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss::RssDatum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rss);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RssDatum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss::RssDatum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss::RssDatum_<ContainerAllocator>& v)
  {
    s << indent << "rss[]" << std::endl;
    for (size_t i = 0; i < v.rss.size(); ++i)
    {
      s << indent << "  rss[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.rss[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS_MESSAGE_RSSDATUM_H
