// Generated by gencpp from file robot_localization_cust/SetPose.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_CUST_MESSAGE_SETPOSE_H
#define ROBOT_LOCALIZATION_CUST_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <robot_localization_cust/SetPoseRequest.h>
#include <robot_localization_cust/SetPoseResponse.h>


namespace robot_localization_cust
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace robot_localization_cust


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_cust::SetPose > {
  static const char* value()
  {
    return "4f3e0bbe7a24e1f929488cd1970222d3";
  }

  static const char* value(const ::robot_localization_cust::SetPose&) { return value(); }
};

template<>
struct DataType< ::robot_localization_cust::SetPose > {
  static const char* value()
  {
    return "robot_localization_cust/SetPose";
  }

  static const char* value(const ::robot_localization_cust::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_cust::SetPoseRequest> should match 
// service_traits::MD5Sum< ::robot_localization_cust::SetPose > 
template<>
struct MD5Sum< ::robot_localization_cust::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_cust::SetPose >::value();
  }
  static const char* value(const ::robot_localization_cust::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_cust::SetPoseRequest> should match 
// service_traits::DataType< ::robot_localization_cust::SetPose > 
template<>
struct DataType< ::robot_localization_cust::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_cust::SetPose >::value();
  }
  static const char* value(const ::robot_localization_cust::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_cust::SetPoseResponse> should match 
// service_traits::MD5Sum< ::robot_localization_cust::SetPose > 
template<>
struct MD5Sum< ::robot_localization_cust::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_cust::SetPose >::value();
  }
  static const char* value(const ::robot_localization_cust::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_cust::SetPoseResponse> should match 
// service_traits::DataType< ::robot_localization_cust::SetPose > 
template<>
struct DataType< ::robot_localization_cust::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_cust::SetPose >::value();
  }
  static const char* value(const ::robot_localization_cust::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_CUST_MESSAGE_SETPOSE_H
