// Generated by gencpp from file jsk_interactive_marker/GetTransformableMarkerColor.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKERCOLOR_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKERCOLOR_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/GetTransformableMarkerColorRequest.h>
#include <jsk_interactive_marker/GetTransformableMarkerColorResponse.h>


namespace jsk_interactive_marker
{

struct GetTransformableMarkerColor
{

typedef GetTransformableMarkerColorRequest Request;
typedef GetTransformableMarkerColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTransformableMarkerColor
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColor > {
  static const char* value()
  {
    return "fe7a7c7dc2d7b081a4b282b1deff45b7";
  }

  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerColor&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerColor > {
  static const char* value()
  {
    return "jsk_interactive_marker/GetTransformableMarkerColor";
  }

  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerColor&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColorRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColor > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerColorRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerColor > 
template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerColorRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColorResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColor > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerColorResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerColor > 
template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerColorResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKERCOLOR_H
