// Generated by gencpp from file jsk_interactive_marker/GetTransformableMarkerFocus.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKERFOCUS_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKERFOCUS_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/GetTransformableMarkerFocusRequest.h>
#include <jsk_interactive_marker/GetTransformableMarkerFocusResponse.h>


namespace jsk_interactive_marker
{

struct GetTransformableMarkerFocus
{

typedef GetTransformableMarkerFocusRequest Request;
typedef GetTransformableMarkerFocusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTransformableMarkerFocus
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocus > {
  static const char* value()
  {
    return "2008933b3c7227647cbe00c74682331a";
  }

  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerFocus&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerFocus > {
  static const char* value()
  {
    return "jsk_interactive_marker/GetTransformableMarkerFocus";
  }

  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerFocus&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocusRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocus > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerFocusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerFocusRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerFocus > 
template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerFocusRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerFocusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocusResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocus > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerFocusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerFocusResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerFocus > 
template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerFocusResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerFocusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKERFOCUS_H
