// Generated by gencpp from file jsk_interactive_marker/GetType.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_GETTYPE_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_GETTYPE_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/GetTypeRequest.h>
#include <jsk_interactive_marker/GetTypeResponse.h>


namespace jsk_interactive_marker
{

struct GetType
{

typedef GetTypeRequest Request;
typedef GetTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetType
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::GetType > {
  static const char* value()
  {
    return "b2d10d8ab8b4019e557c38345217093d";
  }

  static const char* value(const ::jsk_interactive_marker::GetType&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::GetType > {
  static const char* value()
  {
    return "jsk_interactive_marker/GetType";
  }

  static const char* value(const ::jsk_interactive_marker::GetType&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::GetTypeRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetType > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetType >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTypeRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetType > 
template<>
struct DataType< ::jsk_interactive_marker::GetTypeRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetType >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::GetTypeResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetType > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetType >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTypeResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetType > 
template<>
struct DataType< ::jsk_interactive_marker::GetTypeResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetType >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_GETTYPE_H
