// Generated by gencpp from file jsk_interactive_marker/GetTransformableMarkerExistence.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKEREXISTENCE_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKEREXISTENCE_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/GetTransformableMarkerExistenceRequest.h>
#include <jsk_interactive_marker/GetTransformableMarkerExistenceResponse.h>


namespace jsk_interactive_marker
{

struct GetTransformableMarkerExistence
{

typedef GetTransformableMarkerExistenceRequest Request;
typedef GetTransformableMarkerExistenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTransformableMarkerExistence
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistence > {
  static const char* value()
  {
    return "d5188923e69738836fa60c2cc3c5aa81";
  }

  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerExistence&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerExistence > {
  static const char* value()
  {
    return "jsk_interactive_marker/GetTransformableMarkerExistence";
  }

  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerExistence&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistenceRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistence > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistence >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerExistenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerExistenceRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerExistence > 
template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerExistenceRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetTransformableMarkerExistence >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerExistenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistenceResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistence > 
template<>
struct MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::GetTransformableMarkerExistence >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerExistenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerExistenceResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::GetTransformableMarkerExistence > 
template<>
struct DataType< ::jsk_interactive_marker::GetTransformableMarkerExistenceResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::GetTransformableMarkerExistence >::value();
  }
  static const char* value(const ::jsk_interactive_marker::GetTransformableMarkerExistenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_GETTRANSFORMABLEMARKEREXISTENCE_H
