// Generated by gencpp from file jsk_interactive_marker/IndexRequestRequest.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_INDEXREQUESTREQUEST_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_INDEXREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jsk_recognition_msgs/Int32Stamped.h>

namespace jsk_interactive_marker
{
template <class ContainerAllocator>
struct IndexRequestRequest_
{
  typedef IndexRequestRequest_<ContainerAllocator> Type;

  IndexRequestRequest_()
    : index()  {
    }
  IndexRequestRequest_(const ContainerAllocator& _alloc)
    : index(_alloc)  {
  (void)_alloc;
    }



   typedef  ::jsk_recognition_msgs::Int32Stamped_<ContainerAllocator>  _index_type;
  _index_type index;




  typedef boost::shared_ptr< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IndexRequestRequest_

typedef ::jsk_interactive_marker::IndexRequestRequest_<std::allocator<void> > IndexRequestRequest;

typedef boost::shared_ptr< ::jsk_interactive_marker::IndexRequestRequest > IndexRequestRequestPtr;
typedef boost::shared_ptr< ::jsk_interactive_marker::IndexRequestRequest const> IndexRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jsk_interactive_marker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'jsk_interactive_marker': ['/home/simoneforno/simon_ws/src/jsk_visualization/jsk_interactive_markers/jsk_interactive_marker/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7767d85a4611e638acb5e4f67adbc5a";
  }

  static const char* value(const ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7767d85a4611e63ULL;
  static const uint64_t static_value2 = 0x8acb5e4f67adbc5aULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_interactive_marker/IndexRequestRequest";
  }

  static const char* value(const ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_recognition_msgs/Int32Stamped index\n\
\n\
================================================================================\n\
MSG: jsk_recognition_msgs/Int32Stamped\n\
Header header\n\
int32 data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IndexRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_interactive_marker::IndexRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    s << std::endl;
    Printer< ::jsk_recognition_msgs::Int32Stamped_<ContainerAllocator> >::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_INDEXREQUESTREQUEST_H
