// Generated by gencpp from file jsk_interactive_marker/IndexRequest.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_INDEXREQUEST_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_INDEXREQUEST_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/IndexRequestRequest.h>
#include <jsk_interactive_marker/IndexRequestResponse.h>


namespace jsk_interactive_marker
{

struct IndexRequest
{

typedef IndexRequestRequest Request;
typedef IndexRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IndexRequest
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::IndexRequest > {
  static const char* value()
  {
    return "e7767d85a4611e638acb5e4f67adbc5a";
  }

  static const char* value(const ::jsk_interactive_marker::IndexRequest&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::IndexRequest > {
  static const char* value()
  {
    return "jsk_interactive_marker/IndexRequest";
  }

  static const char* value(const ::jsk_interactive_marker::IndexRequest&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::IndexRequestRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::IndexRequest > 
template<>
struct MD5Sum< ::jsk_interactive_marker::IndexRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::IndexRequest >::value();
  }
  static const char* value(const ::jsk_interactive_marker::IndexRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::IndexRequestRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::IndexRequest > 
template<>
struct DataType< ::jsk_interactive_marker::IndexRequestRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::IndexRequest >::value();
  }
  static const char* value(const ::jsk_interactive_marker::IndexRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::IndexRequestResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::IndexRequest > 
template<>
struct MD5Sum< ::jsk_interactive_marker::IndexRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::IndexRequest >::value();
  }
  static const char* value(const ::jsk_interactive_marker::IndexRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::IndexRequestResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::IndexRequest > 
template<>
struct DataType< ::jsk_interactive_marker::IndexRequestResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::IndexRequest >::value();
  }
  static const char* value(const ::jsk_interactive_marker::IndexRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_INDEXREQUEST_H
