// Generated by gencpp from file jsk_interactive_marker/MarkerSetPose.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_MARKERSETPOSE_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_MARKERSETPOSE_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/MarkerSetPoseRequest.h>
#include <jsk_interactive_marker/MarkerSetPoseResponse.h>


namespace jsk_interactive_marker
{

struct MarkerSetPose
{

typedef MarkerSetPoseRequest Request;
typedef MarkerSetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MarkerSetPose
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::MarkerSetPose > {
  static const char* value()
  {
    return "f931e0f5104a6b8bb870d68dbdfaccd9";
  }

  static const char* value(const ::jsk_interactive_marker::MarkerSetPose&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::MarkerSetPose > {
  static const char* value()
  {
    return "jsk_interactive_marker/MarkerSetPose";
  }

  static const char* value(const ::jsk_interactive_marker::MarkerSetPose&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::MarkerSetPoseRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::MarkerSetPose > 
template<>
struct MD5Sum< ::jsk_interactive_marker::MarkerSetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::MarkerSetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::MarkerSetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::MarkerSetPoseRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::MarkerSetPose > 
template<>
struct DataType< ::jsk_interactive_marker::MarkerSetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::MarkerSetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::MarkerSetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::MarkerSetPoseResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::MarkerSetPose > 
template<>
struct MD5Sum< ::jsk_interactive_marker::MarkerSetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::MarkerSetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::MarkerSetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::MarkerSetPoseResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::MarkerSetPose > 
template<>
struct DataType< ::jsk_interactive_marker::MarkerSetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::MarkerSetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::MarkerSetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_MARKERSETPOSE_H
