// Generated by gencpp from file jsk_interactive_marker/RemoveParentMarker.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_REMOVEPARENTMARKER_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_REMOVEPARENTMARKER_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/RemoveParentMarkerRequest.h>
#include <jsk_interactive_marker/RemoveParentMarkerResponse.h>


namespace jsk_interactive_marker
{

struct RemoveParentMarker
{

typedef RemoveParentMarkerRequest Request;
typedef RemoveParentMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveParentMarker
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::RemoveParentMarker > {
  static const char* value()
  {
    return "97181b161a4bd485fbd404baffdcfbf4";
  }

  static const char* value(const ::jsk_interactive_marker::RemoveParentMarker&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::RemoveParentMarker > {
  static const char* value()
  {
    return "jsk_interactive_marker/RemoveParentMarker";
  }

  static const char* value(const ::jsk_interactive_marker::RemoveParentMarker&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::RemoveParentMarkerRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::RemoveParentMarker > 
template<>
struct MD5Sum< ::jsk_interactive_marker::RemoveParentMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::RemoveParentMarker >::value();
  }
  static const char* value(const ::jsk_interactive_marker::RemoveParentMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::RemoveParentMarkerRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::RemoveParentMarker > 
template<>
struct DataType< ::jsk_interactive_marker::RemoveParentMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::RemoveParentMarker >::value();
  }
  static const char* value(const ::jsk_interactive_marker::RemoveParentMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::RemoveParentMarkerResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::RemoveParentMarker > 
template<>
struct MD5Sum< ::jsk_interactive_marker::RemoveParentMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::RemoveParentMarker >::value();
  }
  static const char* value(const ::jsk_interactive_marker::RemoveParentMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::RemoveParentMarkerResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::RemoveParentMarker > 
template<>
struct DataType< ::jsk_interactive_marker::RemoveParentMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::RemoveParentMarker >::value();
  }
  static const char* value(const ::jsk_interactive_marker::RemoveParentMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_REMOVEPARENTMARKER_H
