// Generated by gencpp from file jsk_interactive_marker/SetHeuristicRequest.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETHEURISTICREQUEST_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETHEURISTICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jsk_interactive_marker
{
template <class ContainerAllocator>
struct SetHeuristicRequest_
{
  typedef SetHeuristicRequest_<ContainerAllocator> Type;

  SetHeuristicRequest_()
    : heuristic()  {
    }
  SetHeuristicRequest_(const ContainerAllocator& _alloc)
    : heuristic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _heuristic_type;
  _heuristic_type heuristic;




  typedef boost::shared_ptr< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHeuristicRequest_

typedef ::jsk_interactive_marker::SetHeuristicRequest_<std::allocator<void> > SetHeuristicRequest;

typedef boost::shared_ptr< ::jsk_interactive_marker::SetHeuristicRequest > SetHeuristicRequestPtr;
typedef boost::shared_ptr< ::jsk_interactive_marker::SetHeuristicRequest const> SetHeuristicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jsk_interactive_marker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'jsk_interactive_marker': ['/home/simoneforno/simon_ws/src/jsk_visualization/jsk_interactive_markers/jsk_interactive_marker/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96bf1327fac533122d937324246cbde4";
  }

  static const char* value(const ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96bf1327fac53312ULL;
  static const uint64_t static_value2 = 0x2d937324246cbde4ULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_interactive_marker/SetHeuristicRequest";
  }

  static const char* value(const ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string heuristic\n\
";
  }

  static const char* value(const ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heuristic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHeuristicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_interactive_marker::SetHeuristicRequest_<ContainerAllocator>& v)
  {
    s << indent << "heuristic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.heuristic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETHEURISTICREQUEST_H
