// Generated by gencpp from file jsk_interactive_marker/SetHeuristic.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETHEURISTIC_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETHEURISTIC_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/SetHeuristicRequest.h>
#include <jsk_interactive_marker/SetHeuristicResponse.h>


namespace jsk_interactive_marker
{

struct SetHeuristic
{

typedef SetHeuristicRequest Request;
typedef SetHeuristicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHeuristic
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::SetHeuristic > {
  static const char* value()
  {
    return "96bf1327fac533122d937324246cbde4";
  }

  static const char* value(const ::jsk_interactive_marker::SetHeuristic&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::SetHeuristic > {
  static const char* value()
  {
    return "jsk_interactive_marker/SetHeuristic";
  }

  static const char* value(const ::jsk_interactive_marker::SetHeuristic&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::SetHeuristicRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetHeuristic > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetHeuristicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetHeuristic >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetHeuristicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetHeuristicRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetHeuristic > 
template<>
struct DataType< ::jsk_interactive_marker::SetHeuristicRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetHeuristic >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetHeuristicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::SetHeuristicResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetHeuristic > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetHeuristicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetHeuristic >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetHeuristicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetHeuristicResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetHeuristic > 
template<>
struct DataType< ::jsk_interactive_marker::SetHeuristicResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetHeuristic >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetHeuristicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETHEURISTIC_H
