// Generated by gencpp from file jsk_interactive_marker/SetMarkerDimensions.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETMARKERDIMENSIONS_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETMARKERDIMENSIONS_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/SetMarkerDimensionsRequest.h>
#include <jsk_interactive_marker/SetMarkerDimensionsResponse.h>


namespace jsk_interactive_marker
{

struct SetMarkerDimensions
{

typedef SetMarkerDimensionsRequest Request;
typedef SetMarkerDimensionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMarkerDimensions
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::SetMarkerDimensions > {
  static const char* value()
  {
    return "68f212be16364271f11f516c3f033749";
  }

  static const char* value(const ::jsk_interactive_marker::SetMarkerDimensions&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::SetMarkerDimensions > {
  static const char* value()
  {
    return "jsk_interactive_marker/SetMarkerDimensions";
  }

  static const char* value(const ::jsk_interactive_marker::SetMarkerDimensions&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::SetMarkerDimensionsRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetMarkerDimensions > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetMarkerDimensionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetMarkerDimensions >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetMarkerDimensionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetMarkerDimensionsRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetMarkerDimensions > 
template<>
struct DataType< ::jsk_interactive_marker::SetMarkerDimensionsRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetMarkerDimensions >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetMarkerDimensionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::SetMarkerDimensionsResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetMarkerDimensions > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetMarkerDimensionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetMarkerDimensions >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetMarkerDimensionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetMarkerDimensionsResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetMarkerDimensions > 
template<>
struct DataType< ::jsk_interactive_marker::SetMarkerDimensionsResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetMarkerDimensions >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetMarkerDimensionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETMARKERDIMENSIONS_H
