// Generated by gencpp from file jsk_interactive_marker/SetPose.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETPOSE_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/SetPoseRequest.h>
#include <jsk_interactive_marker/SetPoseResponse.h>


namespace jsk_interactive_marker
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::SetPose > {
  static const char* value()
  {
    return "a0d9547b398ab09cc2eb51b64661fda0";
  }

  static const char* value(const ::jsk_interactive_marker::SetPose&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::SetPose > {
  static const char* value()
  {
    return "jsk_interactive_marker/SetPose";
  }

  static const char* value(const ::jsk_interactive_marker::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::SetPoseRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetPose > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetPoseRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetPose > 
template<>
struct DataType< ::jsk_interactive_marker::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::SetPoseResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetPose > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetPoseResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetPose > 
template<>
struct DataType< ::jsk_interactive_marker::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetPose >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETPOSE_H
