// Generated by gencpp from file jsk_interactive_marker/SetTransformableMarkerFocus.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERFOCUS_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERFOCUS_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/SetTransformableMarkerFocusRequest.h>
#include <jsk_interactive_marker/SetTransformableMarkerFocusResponse.h>


namespace jsk_interactive_marker
{

struct SetTransformableMarkerFocus
{

typedef SetTransformableMarkerFocusRequest Request;
typedef SetTransformableMarkerFocusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTransformableMarkerFocus
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocus > {
  static const char* value()
  {
    return "2008933b3c7227647cbe00c74682331a";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerFocus&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerFocus > {
  static const char* value()
  {
    return "jsk_interactive_marker/SetTransformableMarkerFocus";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerFocus&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocusRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocus > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerFocusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerFocusRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerFocus > 
template<>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerFocusRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerFocusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocusResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocus > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerFocusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerFocusResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerFocus > 
template<>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerFocusResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetTransformableMarkerFocus >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerFocusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERFOCUS_H
