// Generated by gencpp from file jsk_interactive_marker/SetTransformableMarkerColor.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERCOLOR_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERCOLOR_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/SetTransformableMarkerColorRequest.h>
#include <jsk_interactive_marker/SetTransformableMarkerColorResponse.h>


namespace jsk_interactive_marker
{

struct SetTransformableMarkerColor
{

typedef SetTransformableMarkerColorRequest Request;
typedef SetTransformableMarkerColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTransformableMarkerColor
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColor > {
  static const char* value()
  {
    return "6da9e77546dd19426d1dc251fb18d20e";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerColor&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerColor > {
  static const char* value()
  {
    return "jsk_interactive_marker/SetTransformableMarkerColor";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerColor&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColorRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColor > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerColorRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerColor > 
template<>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerColorRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColorResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColor > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerColorResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::SetTransformableMarkerColor > 
template<>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerColorResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SetTransformableMarkerColor >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERCOLOR_H
