// Generated by gencpp from file jsk_interactive_marker/SetTransformableMarkerPoseRequest.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERPOSEREQUEST_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace jsk_interactive_marker
{
template <class ContainerAllocator>
struct SetTransformableMarkerPoseRequest_
{
  typedef SetTransformableMarkerPoseRequest_<ContainerAllocator> Type;

  SetTransformableMarkerPoseRequest_()
    : target_name()
    , pose_stamped()  {
    }
  SetTransformableMarkerPoseRequest_(const ContainerAllocator& _alloc)
    : target_name(_alloc)
    , pose_stamped(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_name_type;
  _target_name_type target_name;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_stamped_type;
  _pose_stamped_type pose_stamped;




  typedef boost::shared_ptr< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTransformableMarkerPoseRequest_

typedef ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<std::allocator<void> > SetTransformableMarkerPoseRequest;

typedef boost::shared_ptr< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest > SetTransformableMarkerPoseRequestPtr;
typedef boost::shared_ptr< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest const> SetTransformableMarkerPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jsk_interactive_marker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'jsk_interactive_marker': ['/home/simoneforno/simon_ws/src/jsk_visualization/jsk_interactive_markers/jsk_interactive_marker/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e19607b29b4528e87feff290fe261191";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe19607b29b4528e8ULL;
  static const uint64_t static_value2 = 0x7feff290fe261191ULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_interactive_marker/SetTransformableMarkerPoseRequest";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target_name\n\
geometry_msgs/PoseStamped pose_stamped\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_name);
      stream.next(m.pose_stamped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTransformableMarkerPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_interactive_marker::SetTransformableMarkerPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target_name);
    s << indent << "pose_stamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_stamped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SETTRANSFORMABLEMARKERPOSEREQUEST_H
