// Generated by gencpp from file jsk_interactive_marker/SnapFootPrint.msg
// DO NOT EDIT!


#ifndef JSK_INTERACTIVE_MARKER_MESSAGE_SNAPFOOTPRINT_H
#define JSK_INTERACTIVE_MARKER_MESSAGE_SNAPFOOTPRINT_H

#include <ros/service_traits.h>


#include <jsk_interactive_marker/SnapFootPrintRequest.h>
#include <jsk_interactive_marker/SnapFootPrintResponse.h>


namespace jsk_interactive_marker
{

struct SnapFootPrint
{

typedef SnapFootPrintRequest Request;
typedef SnapFootPrintResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SnapFootPrint
} // namespace jsk_interactive_marker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_interactive_marker::SnapFootPrint > {
  static const char* value()
  {
    return "e5091889756b723fad89a5ee8ac81396";
  }

  static const char* value(const ::jsk_interactive_marker::SnapFootPrint&) { return value(); }
};

template<>
struct DataType< ::jsk_interactive_marker::SnapFootPrint > {
  static const char* value()
  {
    return "jsk_interactive_marker/SnapFootPrint";
  }

  static const char* value(const ::jsk_interactive_marker::SnapFootPrint&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_interactive_marker::SnapFootPrintRequest> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SnapFootPrint > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SnapFootPrintRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SnapFootPrint >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SnapFootPrintRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SnapFootPrintRequest> should match 
// service_traits::DataType< ::jsk_interactive_marker::SnapFootPrint > 
template<>
struct DataType< ::jsk_interactive_marker::SnapFootPrintRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SnapFootPrint >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SnapFootPrintRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_interactive_marker::SnapFootPrintResponse> should match 
// service_traits::MD5Sum< ::jsk_interactive_marker::SnapFootPrint > 
template<>
struct MD5Sum< ::jsk_interactive_marker::SnapFootPrintResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_interactive_marker::SnapFootPrint >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SnapFootPrintResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_interactive_marker::SnapFootPrintResponse> should match 
// service_traits::DataType< ::jsk_interactive_marker::SnapFootPrint > 
template<>
struct DataType< ::jsk_interactive_marker::SnapFootPrintResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_interactive_marker::SnapFootPrint >::value();
  }
  static const char* value(const ::jsk_interactive_marker::SnapFootPrintResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_INTERACTIVE_MARKER_MESSAGE_SNAPFOOTPRINT_H
